modLoader = "javafml"
loaderVersion = "[4,)"
issueTrackerURL = "https://github.com/Slexom/animal-feeding-trough/issues"
license = "MIT"

[[mods]]
modId = "animal_feeding_trough"
version = "1.1.2"
displayName = "Animal Feeding Trough"
authors = "Slexom"
description = '''
-
'''
logoFile = "icon.png"

[[dependencies.animal_feeding_trough]]
modId = "minecraft"
type = "required"
versionRange = "[1.21.3,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.animal_feeding_trough]]
modId = "neoforge"
type = "required"
versionRange = "[21.3.0-beta,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.animal_feeding_trough]]
modId = "architectury"
type = "required"
versionRange = "[14,)"
ordering = "AFTER"
side = "BOTH"

[[mixins]]
config = "mixins.animal_feeding_trough.json"
